version = 5.7.0
archive_dir = /etc/letsencrypt/archive/capoeira.booktolife.com
cert = /etc/letsencrypt/live/capoeira.booktolife.com/cert.pem
privkey = /etc/letsencrypt/live/capoeira.booktolife.com/privkey.pem
chain = /etc/letsencrypt/live/capoeira.booktolife.com/chain.pem
fullchain = /etc/letsencrypt/live/capoeira.booktolife.com/fullchain.pem
[renewalparams]
account = acabcf9404a80fd9bc4eaee7f5aede48
authenticator = webroot
webroot_path = /var/www/certbot,
server = https://acme-v02.api.letsencrypt.org/directory
key_type = ecdsa
[[webroot_map]]
capoeira.booktolife.com = /var/www/certbot
